### ISSUE TITLE
Rate-limit resets

### ISSUE THREAD

**Issue by MaddieM4** [campadrenalin/idle.js#1]
Every reset involves destroying a setTimeout timer, and creating a new one. We also do a string comparison to see if we need to do a this._broadcast('wake'). It's not clear how much overhead that is, for a function that could run many times per second when rapidly scrolling/moving the mouse.

An option, is that after every reset, we temporarily turn off the ability to reset again for the next T milliseconds. We would implement this with:
- A flag
- An additional timer, which resets the flag
- We check the flag at the top of reset(), and set it to true at the bottom of reset().

However, it's an open question whether this additional complexity would simply make things worse, for example, by sabotaging compilation. And currently, the overhead is invisible for modern browsers. It _would_ be worthwhile to test on crappy mobile devices, though, where both the browser optimization and hardware capability will be lacking.

**Comment by nebulous** [comment]
Debouncing calls to all hooks[] events to a specified master granularity would be neato. I too don't know if it would be fighting browser optimizations, but it _would_ be cool.

**Comment by MaddieM4** [comment]
We really need a mechanism for benchmarking, otherwise we'll never have any insight into whether early-returns regress the performance unintuitively. It's all just speculation until we have numbers.

I can tell you that I've tried the idle.js demo on a mobile device as a sanity check, and the experience was perfectly smooth. Perhaps that would not be the case on a more complex page, because of event bubbling through deep DOM hierarchies and competition for the single JS computation thread. But being able to measure the CPU time idle.js is using would be a big boon, at least for seeing how much headroom is left over, and which approach is more efficient.

**Comment by MaddieM4** [comment]
Some very basic playing around in the Chrome profiler the other day suggests that even for one of the most heavily JIT-optimized interpreters in the modern browser space, the browser API overhead is high enough to make throttling worthwhile. I'm going to write a proper implementation and test in Chrome and Firefox tonight.

**Comment by MaddieM4** [comment]
Wrote up a patch, and it works. In my somewhat unscientific tests, the unpatched version uses a higher percent of CPU time _each_ for `setTimeout` and `clearTimeout`, than the patched version uses for all of `self._reset()` _combined_.

Old `_reset`: 6.98% (2.11% setTimeout, 1.71% clearTimeout)
New `_reset`: 1.06%

While the old version has yet to present any visible performance degradation on any platform or scenario I've tried, we should always try to be our best, and this is a very clear win.
